### ISSUE TITLE
determinism of simulation

### ISSUE THREAD

**Issue by pgruenbacher** [MengeCrowdSim/Menge#105]
I know there's the project-level seed for the random generators. How feasible is this library for gamedev-level determinism? I think the first issue that comes to my mind is that I need to make sure the RandomGenerators aren't being called while in the omp parallel for loops. 

I suppose it may also need to be compiled with fixed point precision instead of float precision. Does that seem feasible?

https://gafferongames.com/post/deterministic_lockstep/

**Comment by pgruenbacher** [comment]
Hm so yea it seems what when it gets down to the units interacting with on another the simulation can diverge fairly quickly. 

![image](https://user-images.githubusercontent.com/3332598/45001266-b8cb7a00-af99-11e8-953e-b298dc870179.png)

**Comment by pgruenbacher** [comment]
![double](https://user-images.githubusercontent.com/3332598/45001331-2ecfe100-af9a-11e8-825a-1bf828d120a9.gif)

**Comment by pgruenbacher** [comment]
ran periodic with random="10" on the project. Pretty sure it's diverging. I may try to recompile with OMP just to make sure it's not a parallel issue.

![ezgif-4-efc68f059e](https://user-images.githubusercontent.com/3332598/45001475-52dff200-af9b-11e8-8d83-8b0b3cdd0a0d.gif)

**Comment by pgruenbacher** [comment]
![diverged2](https://user-images.githubusercontent.com/3332598/45001648-e4039880-af9c-11e8-85ef-8ec8f5178353.png)

better proof. same time. same random seed. but selected 115 agent has differing position floats.

**Comment by pgruenbacher** [comment]
![screenshot from 2018-09-03 17-31-17](https://user-images.githubusercontent.com/3332598/45001903-67be8480-af9f-11e8-8b1f-892ada9dc50a.png)

simulation *is* deterministic when openmpi turned off...

**Comment by pgruenbacher** [comment]
```
		bool FSM::doStep() {
			// NOTE: This is a cast from size_t to int to be compatible with older implementations
			//		of openmp which require signed integers as loop variables
			SIM_TIME = this->_sim->getGlobalTime();
			EVENT_SYSTEM->evaluateEvents();
			int agtCount = (int)this->_sim->getNumAgents();
			size_t exceptionCount = 0;
			#pragma omp parallel for ordered reduction(+:exceptionCount)
			for ( int a = 0; a < agtCount; ++a ) {
				#pragma omp ordered
				{Agents::BaseAgent * agt = this->_sim->getAgent( a );
				try {
					advance( agt );
					this->computePrefVelocity( agt );
				} catch ( StateException & e ) {
					logger << Logger::ERR_MSG << e.what() << "\n";
					++exceptionCount;
				}}
			}
			if ( exceptionCount > 0 ) {
				throw FSMFatalException();
			}
			return this->allFinal();
		}```

Adding a omp ordered keyword seemed to do the trick for syncing the periodic example. I guess cause the computePrefVelocity is being set in parallel, which could effect the other advances? I'm not sure...

**Comment by MengeCrowdSim** [comment]
Looks like I'm late to this party.  All I can do is confirm all of the things you've discovered. When evaluating the simulation in parallel, determinism flies out the window and for the reason you've concluded -- agents can enter/leave states in arbitrary order during step advancement (due to the method of parallelization). If any of the BFSM components has a *single* number generator that is shared across all of its agents (which most do), then the assignment of those random numbers are not deterministic.

I'm glad the ordered keyword solves the problem. You feel like putting that in a PR?

**Comment by pgruenbacher** [comment]
hm. well  I'm guessing  the ordered keywordis gonna cause some performance issues since it negates the parallelism benefit. I think the real reason is because the RandGenerator aren't thread-safe and they're being used in both test cases I've done (Vec2Dgenerator by the teleport action) and (Timer random) in my custom game case. Let's see if that will resolve the issue. If so, then what I can instead do is have the random generator return random values using the agent id as a seed in combo with a seed that changes each SIM_TIME_STEP. Heck maybe just global_seed + Menge::SIME_TIME + agent->_id. That should mantain pseudo randomness while ignoring a local seed change.

**Comment by pgruenbacher** [comment]
yep changing timers from uniform dist to constant value resolves that problem. I'll move forward on implementing some new function signatures for the random distributors that accept agent id as a seed (and upate the fsm classes as well that use the distributors). 

As for the float vs fixed point issue. My game involves 4000+ agents potentially, so I'll need some sort of determinism for predictive client-side, but I'll also probably need to do server-client updates to keep the game in sync no matter what, since it's not worth trusting deterministic lock-step purely. so I may be able to get away with float desyncing issues across different machines.

**Comment by pgruenbacher** [comment]
Actually maybe what I'll do is have each agent mantain it's own random _seed attribute

**Comment by pgruenbacher** [comment]
hm actually trying to get the random generators thread-deterministic is actually difficult when trying to also mantain pseudo-randomness... any ideas?

**Comment by pgruenbacher** [comment]
Right, I guess that makes sense since different random generator types for
different elements would need to maintain their own seeds. Ok that makes
sense.

Only thing left to investigate for me is how feasible it is to used a fixed
point vs float everywhere.

**Comment by MengeCrowdSim** [comment]
Can you elaborate on what you're hoping to accomplish by using fixed-point computation

**Comment by MengeCrowdSim** [comment]
I generally suspect that moving from floating- to fixed-point computation will be intractable. I'd need to go through and template the scalars and then provide a fixed-point scalar. That is a *huge*, far-reaching endeavor. To see what that kind of thing looks like, take a look at https://github.com/RobotLocomotion/drake as an example.

**Comment by MengeCrowdSim** [comment]
So, it may not be *completely* intractable. Some of my underlying mathematical components are already vectorized on scalar (Vector2/3 Matrix). So providing a fixed-point scalar would make those possible. And then that would have to smear over to the floating point generators (becoming "Real" generators for any "real" scalar). And then hitting all of the local members.... And then implicit conversion between fixed-point and floating-point at the visualization interface.  Yikes, still lots of work.

I definitely support the idea of getting your network up and running first and seeing how much of a pain point this is. 

And now, for my own curiosity, would you pre-condition all of your fixed-point values based on having a fixed simulation domain? That would certainly provide the advantage of not having to do run-time conditioning. it does ruin some of the Menge tricks of teleporting agents off to some distant domain (unless you encoded "infinity" in your fixed-point representation.) While I've toyed with fixed-point, I've never actually tried to engineer a system that would use them in a disciplined manner, so I'm curious as to some of the details.

Also, here was an interesting read on the subject of non-determinism of floating-point values:

https://randomascii.wordpress.com/2013/07/16/floating-point-determinism/

Given that the majority of the operations are linear algebra, you may not have too many determinism issues. Transcendentals will be the biggest issue but, I hope, they don't crop up too much.

**Comment by pgruenbacher** [comment]
Yea I guess I'd do fixed simulation domain. I have a is_dead() base agent method in my github fork that I use to handle agents that should be ignored so I haven't needed a teleport action yet to disappear agents out of the domain. Yea the article is what mostly informed me. I think a good network system would still try to keep all the agents synced regardless of the determinism, since if you want players to hot-join a server game you'd have to be able to send them the current serialized game state anyways (or fast-forward the entire simulation through the player action list to the current time). A perfectly deterministic simulation can do stuff like replays too with a small file of all the player actions and events. Of course Total War has shown how fragile those game replays can be. Stuff is tough.

**Comment by pgruenbacher** [comment]
but again I should just test the simulations on different machines first anyways.

**Comment by pgruenbacher** [comment]
![image](https://user-images.githubusercontent.com/3332598/45113162-952e3e00-b117-11e8-855d-4edb584f677a.png)

periodic deterministic now too. I'll make a PR for the vanilla files I changed.

**Comment by pgruenbacher** [comment]
actually here's the https://github.com/pgruenbacher/Menge/blob/determinism/src/Menge/MengeCore/Math/RandGenerator.cpp updated random generator code in my fork, may be easier to inspect this way. You'll see I hacked in a MAX_AGENT const and a fixed std::array for tracking per agent seeds in the random generator.
