### ISSUE TITLE
Make agents follow one another 

### ISSUE THREAD

**Issue by saruvora** [MengeCrowdSim/Menge#135]
How can I make agents follow each other ? from different groups. I am using the XML files.  
How can I generate NavMesh and roadmap for agents?

**Comment by curds01** [comment]
Related to my response on https://github.com/curds01/MengeUtils/issues/4. Go ahead and email me at `menge@cs.unc.edu` and we can have this conversation there.  (Although, I might end up extracting an answer and putting it here as well.)
