### ISSUE TITLE
Pedestrian Simulation - PedVO

### ISSUE THREAD

**Issue by dkal3** [MengeCrowdSim/Menge#136]
Hi!!
I would like to know how I can open a PedVO simulator window in Menge, so I can see the simulation time of PedVO algorithm.
I can run all the examples with this command
 menge.exe -p ..\examples\core\headon.xml
as you refer in the instructions, but I can see the information for ORCA algorithm.
Sorry if my question seems simple, but I am a bit confused.
Thank you!!!!!

**Comment by douglasbandeiraivo** [comment]
Try this command:
menge.exe -p ..\examples\core\headon.xml -m pedvo


Em seg, 12 de ago de 2019 06:11, dkal3 <notifications@github.com> escreveu:

**Comment by curds01** [comment]
Just as a side comment. It really warms my heart that someone else answered the question. That's the beginnings of a community. Thanks @douglasbandeiraivo. :)

**Comment by douglasbandeiraivo** [comment]
:)

Em seg, 12 de ago de 2019 12:15, curds01 <notifications@github.com>
escreveu:

**Comment by dkal3** [comment]
Thank you very much!!!It works!!!!
<3
