### ISSUE TITLE
HOW TO RUN MENGE ON MAC ?

### ISSUE THREAD

**Issue by geehadq** [MengeCrowdSim/Menge#161]
Hello,
It might sound dumb ,but I'm not quite good at programming using C++ though I managed to build the project on Mac. However, executing Menge remains unclear to me (typing  `./menge` gives a segmentation fault).
Please I'm in need of this project for academic purposes ASAP.
Best regards,

ME

**Comment by chraibi** [comment]
Running Menge is described in the readme. OSX is like Linux:
https://github.com/MengeCrowdSim/Menge#running-simulations

Did you build Menge properly?

https://github.com/MengeCrowdSim/Menge#mac-osx

Running the examples should not give you any SegFault. If so, it is a good idea to give more details and screenshots.

PS: ASAP is not gonna work either. Patience might!

**Comment by geehadq** [comment]
Hey Chraibi,
I finally managed to run Menge thanks to the fix proposed by @ajvani for MacOSX on this page : 

#81 

Ultimately, I am going to close the issue.

Best regards,

PS: Thanks for the swift replying @chraibi.
