### ISSUE TITLE
CMake package requirements

### ISSUE THREAD

**Issue by chraibi** [MengeCrowdSim/Menge#40]
Should CMake fail, when requirements of Menge are not met? 

![screen shot 2017-02-13 at 13 08 34](https://cloud.githubusercontent.com/assets/5772973/22882890/a89e2bb6-f1ed-11e6-9028-2534f6ffbe21.png)

**Comment by chraibi** [comment]
Maybe this should go to the README file

```
sudo apt-get install libsdl-ttf2.0-dev libsdl-image1.2-dev libsdl1.2-dev
```
(with these installation Menge compiles under Ubuntu!)

**Comment by curds01** [comment]
I agree.  There are some (less detailed) instructions on Menge's website:

http://gamma.cs.unc.edu/Menge/learn/gettingStarted.html

But several things need to happen: 
1) Readme should either contain or link to all the instructions necessary to build.
2) The build instructions need to be complete and explicit.

**Comment by chraibi** [comment]
I would say, some description similar to  the typical `configure; make; make install` should be ok.

- `cmake`. Check if every thing is installed. if not install whatever is missing.
- If successful `make`
- If successful try `Menge -p XYZ` to run an example simulation
