### ISSUE TITLE
Control the visualisation 

### ISSUE THREAD

**Issue by chraibi** [MengeCrowdSim/Menge#41]
Is there some known keystrokes that enables controling the visualisation? 
pressing "space" starts the visualisation.

But, what about "back", "forth", "zoom", etc?

![screen shot 2017-02-13 at 13 36 49](https://cloud.githubusercontent.com/assets/5772973/22883661/80575610-f1f1-11e6-9fd2-7809abf32a30.png)

**Comment by chraibi** [comment]
per change when pressing "h" I got this 

```
Viewer controls:
  Quit the program ............ Ctrl + q
  Camera controls:
    Ctrl + Left Mouse ......... ROTATION
    Ctrl + Shift + Left Mouse.. MOVE
    Shift + Left Mouse ........ ZOOM
    'o' ....................... Orthographic view
    'p' ....................... Perspective view
    'x' ....................... Look along x-axis
    Shift + 'x'................ Look along negative x-axis
    'y' ....................... Look along y-axis
    Shift + 'y'................ Look along negative y-axis
    'z' ....................... Look along z-axis
    Shift + 'z'................ Look along negative z-axis
    Ctrl + 'c'................. Display camera parameters to the console
    Ctrl + '1'-'9'............. Switch cameras (if a camera exists)
  Playback:
    spacebar .................. Stop/start playback
    RIGHT arrow ............... Advance one frame (when stopped)
  Output images ............... Ctrl + o
```

No LEFT arrow?

**Comment by curds01** [comment]
This is a very simple visualizer.  It doesn't have any cached results (which is why you can't step backwards in time.)  The intent is to create an alternate visualizer that is more user friendly.  I've got one started.  But only so many hours in a week...

**Comment by chraibi** [comment]
I see. Is the transparency a feature or a bug (related to my system)?

**Comment by curds01** [comment]
I would assume the transparency is some conflict between SDL and your system.  There is a rendering problem we've encountered in the past related to SDL.  I'm not sure what this one could be attributed to.

**Comment by MengeCrowdSim** [comment]
Closed as a won't fix. The conversation helps document the simple viewer controls.
