### ISSUE TITLE
Nav mesh obstacle failure -- obstacles selected from wrong level

### ISSUE THREAD

**Issue by curds01** [MengeCrowdSim/Menge#6]
When using a navigation mesh-based spatial query object, when there is a navigation mesh polygon *over* an agent, the obstacles selected for that agent are the covering polygon and not the polygon the agent is actually on.

In the attached example (images shown below), the agent is walking down a ramp and about to cross under an overhang.  As soon as the agent center crosses into the projection of the upper polygon, its obstacles will come from that polygon and the agent will *not* be able reach its goal because the upper polygon has an obstacle between the agent and its goal.

The project for evaluating this can be found below.

![image](https://cloud.githubusercontent.com/assets/22562264/19018590/4771f00a-881d-11e6-9a15-881198d5598b.png)
Fig 1. Agent walking down a ramp, underneath an overhang.

![image](https://cloud.githubusercontent.com/assets/22562264/19018592/530fedf4-881d-11e6-99fe-22b0574205d2.png)
Fig 2. Agent about to pass under the overhang.

[nav_mesh_fail.txt](https://github.com/MengeCrowdSim/Menge/files/504776/nav_mesh_fail.txt)
[nav_mesh_failB.txt](https://github.com/MengeCrowdSim/Menge/files/504780/nav_mesh_failB.txt)
[nav_mesh_failS.txt](https://github.com/MengeCrowdSim/Menge/files/504778/nav_mesh_failS.txt)
[nav_mesh_failV.txt](https://github.com/MengeCrowdSim/Menge/files/504777/nav_mesh_failV.txt)
[simple_NM.txt](https://github.com/MengeCrowdSim/Menge/files/504779/simple_NM.txt)

**Comment by curds01** [comment]
The interface receives a pointer to a `ProximityFilter`.  Generally, the pointer is asked for its query point and that query point is used to look up the node corresponding to the point.  This is why the wrong node (aka polygon) is used, because this point is determined in a top-down manner.

However, if we recognize the types of classes that are tracked by the `NavMeshLocalizer`, we can see if the filter object is one of those objects.  If it is, we can simply use that object to look up the correct node in the localizer.  Currently, there is only one tracked class: `BaseAgent`.  That is enough for now.  If we end up tracking other entities, they will have to be added to this test.

**Comment by MengeCrowdSim** [comment]
Solution Merged
