### ISSUE TITLE
How to read SCB output file?

### ISSUE THREAD

**Issue by zhangl64** [MengeCrowdSim/Menge#64]
Hi, how can we open and see the output SCB file? Any software that we need to install? Thanks.

**Comment by MengeCrowdSim** [comment]
Sorry for the delayed response:

There are three options:
1. I have an informal set of python tools I use when working with Menge. They include the ability to read scb files (and perform various types of analysis). I'm still documenting them. I was thinking of simply pushing them up into a repository that Menge users can pull from.
2. It would be simple enough for me to create a utility in Menge that would create an ascii csv file from an scb file. Then you could consume it any way you like.
3. I could modify the output such that you can choose between an `.scb` file and an `.sca` file (the ascii equivalent). I'd always intended to have `.sca` as an output, but when modeling 10-30K agents, ascii files get ridiculously large very quickly.

Preferences?

**Comment by zhangl64** [comment]
Hi @MengeCrowdSim , thanks for your reply. Since I would like to try Menge with large crowd in the near future (probably more than 30k), I will pass Option 3 first. 
For Options 1 and 2, it seems like that Option 2 is a straightforward approach to read output files. So I'd like to choose Option 2 if it doesn't cause you a lot of work, because I guess it will fulfil all my needs now. 
For Option 1, if you could send me some sample tools that I can simply try them by myself without documents, that is good to me. Otherwise, I would be happy to wait for the new repository, and pull it in the future.
Thanks a lot!

**Comment by curds01** [comment]
Fastest is to pull this repository (I just set it up):

https://github.com/curds01/MengeUtils/tree/master

If you message me with an email address, I can give you access to the documentation that exists and help you use it. There are a number of very useful utilities (such as cropping, sampling, visualizing, etc., scb files).

**Comment by zhangl64** [comment]
Hi @curds01 , I'll pull the repository and try it, and my email address is 
huntchang830@gmail.com 
Thanks for your kind help~
