### ISSUE TITLE
Covert distance/speed units in local coordinate system to units in real world?

### ISSUE THREAD

**Issue by zhangl64** [MengeCrowdSim/Menge#65]
Hi, I have a naive question here - can we convert the distance and speed units in Menge's local coordinate system to the corresponding units in real world?
For example, in the scene specification, when we set neighbor_dist="1", can we say that "1" equals to "x" meters (where "x" is the physical space in real world)?
Another example is the speed, e.g., pref_speed="1.04", can we convert its unit to meters per second?
Thanks.

**Comment by MengeCrowdSim** [comment]
I have good news for you:

1) The units can be anything you like. It's just a case of being consistent and knowing how to interpret.
2) Menge's examples all (should) use SI. So, meters, meters per second, etc. A circle of approx 0.2 m radius is human sized.  Average walking speed is 1.3 m/s. If you see an example that used units other than those, please let us know.

**Comment by zhangl64** [comment]
@MengeCrowdSim Who don't like good news:) Thank you so much for your help~
