### ISSUE TITLE
Can we choose to disable/enable the GUI in Menge?

### ISSUE THREAD

**Issue by zhangl64** [MengeCrowdSim/Menge#69]
Hi,
In Menge, is there a "magic" setting to disable or enable the GUI as needed?
If it has to be done in the source code, what do you suggest as a starting point?

Thanks a lot.

**Comment by zhangl64** [comment]
I guess that I can do it by controlling the `visualize` flag :)

**Comment by MengeCrowdSim** [comment]
I'm glad you found this.  Certainly, the visualization was meant to be a convenience and not a burden. In my own research, there have been many times where I simply wanted to run simulation after simulation, caching the simulation results. And decoupling it from visualization was absolutely necessary.

Let me know if this meets your needs.

**Comment by zhangl64** [comment]
Yes @MengeCrowdSim , just as you said and I quoted here:

>  to run simulation after simulation, caching the simulation results.

You have been there, and that's exactly what I need. Thanks 👍
