### ISSUE TITLE
Can I install Menge on Ubuntu 16.04 successfully?

### ISSUE THREAD

**Issue by Aaricis** [MengeCrowdSim/Menge#83]

**Comment by chraibi** [comment]
Yes you can. Did you try?

**Comment by Aaricis** [comment]
Not yet, but I will try.

**Comment by curds01** [comment]
Specifically, you'll have to build from source. But the instructions are in the [README.md](https://github.com/MengeCrowdSim/Menge/blob/master/README.md). It should be simple.

**Comment by Aaricis** [comment]
Thanks a lot
