### ISSUE TITLE
Is this real? :)

### ISSUE THREAD

**Issue by mimooh** [MengeCrowdSim/Menge#89]
I am really impressed by reading the papers. Does Menge really do all this? 

For our software (https://github.com/aamks/aamks) which is about fires and humans evacuation, we need a tool to:
1) create navmesh
2) query navmesh
3) avoid dynamic obstacles, say hundreds of humans evacuating

We need 3D - humans evacuate from multi storey buildings.

We were considering recast and detour, but there are two issues:
1) https://github.com/recastnavigation/recastnavigation/issues/305
2) based on what I read on forums, integrating Recast and Detour is a real challenge and I am not that much a C++ programmer

People say Recast and Detour is the state of the art when it comes to navmesh. Do you know how Menge compares here? We are more into crowd evacuation business than games business, so perhaps Menge would suit us even better. Performance is not that of an issue to us since we don't do any real time rendering. When it comes to 3) Recast uses RVO2, but with Menge it seems we could try various models. This just seems awesome. So basically, is this software production ready?

**Comment by curds01** [comment]
Is it real? For a given value of "reality", yes.  However, reading your question, I suspect that Menge may not yet be the tool for you.

1. It takes a navmesh as an input -- it doesn't create them itself. So, if you need to generate a nav mesh, Menge won't do it.
2. That said, once the navmesh exists (and is expressed in Menge's very idiosyncratic way), yes, it queries the navmesh, and avoids dynamic obstacles -- although, in this case, dynamic obstacles is *strictly* other agents. It doesn't currently handle dynamic navmesh (e.g., pathways which become occluded, etc.)
  - Historically, we've created our navmesh by hand in a modeling package and then used a utility to convert an obj version of it into Menge's representation. Clunky but it's gotten us there.
  - There's also a Menge GUI application in the works that will eventually allow authoring scenarios (including navigation meshes) in a 3D app. Although that is a *long* way away.
3. It *is* true that you can run Menge with arbitrary pedestrian models. The implementations in Menge's example plugins are *not* guaranteed to be wholly robust. 
4. The question of "3D". In what sense? Menge can support simulation in a 3D environment (primarily using a navigation mesh). However, Menge's built-in visualization is quite simplistic -- agents are rendered as cylinders. Some of the Menge-related videos that show 3D humans would use a stand-alone visualizer that, unfortunately, we can't distribute. A unity-based, open-license 3D visualizer is in the works, but we have very limited resources.

So, I can't give a definitive answer as to whether Menge will serve your purpose. But as you characterize your needs, I can tell you where Menge will fit and where it might not.

**Comment by mimooh** [comment]
Wow, quick answer! :)

1. So we need to create a navmesh ourselves, I see. The easy solution is to run a Blender script which would return the navmesh (Recast and Detour's one). The desired solution would be the real integration of Recast or such.

2. "idiosyncratic way" - once the input/output formats are known, hopefully the converter wouldn't be much of an issue. Currently I am most concerned about navmesh queries, since I know the least about it. Is  yours of a good quality? In Blender the agents wouldn't always respect the Z coordinate - they would go to the right X,Y on their floor instead of moving to another floor first. 

2b. Menge GUI app - consider using Blender. That what I did. It has a python interface and allows for scripting. It has Recast and Detour integrated and automatically creates navmesh for the given geometry. However, navmesh queries, dynamic obstacles avoidance (RVO2) didn't seem to work that well, so I started to look for something else. But as a geometry creator and visalization / animation tool it is awesome.

4. I meant simulating in a 3D environment. Visualization is a separate thing and not an issue to us.

I wonder how much in common our projects have. Menge is lowlevel for what we need in aamks. I speak python more than C++, but perhaps we could cooperate in some way. Would you rather choose to code your own navmesh or see about Recast integration?

**Comment by curds01** [comment]
So, Menge uses two mechanisms to keep agents *on* the navigation mesh. (See [`$MENGE$/examples/core/navMeshPlacement.xml`](https://github.com/MengeCrowdSim/Menge/blob/master/examples/core/navMeshPlacement.xml) for a simple example.) This example not only shows placement on the navigation mesh, but emphasizes the fact that the navigation mesh doesn't have to be a simple heightfield. This navmesh can't simply be projected down onto a plane. The [`$MENGE$/examples/core/soccer.xml`](https://github.com/MengeCrowdSim/Menge/blob/master/examples/core/soccer.xml) example is another (similar non-planar topology). The navigation mesh works in conjunction with an `Elevation` element.

I hadn't considered using Blender for that purpose at all. I've been contemplating doing python bindings for Blender (and the most limited are possible now via the limited exposed c-api and ctypes). That might be a good motivation, although I haven't played with blender at all.

Also, in the long run, integrating Recast would be an unfettered good. It's just been a case of time and motivation. Generally, the squeaky wheel has been getting the grease.

So, I'd be happy to work with you in pushing Menge's functionality in those directions. We can work up a plan and see what we can produce.

**Comment by mimooh** [comment]
> So, I'd be happy to work with you in pushing Menge's functionality in those directions. We can work up a plan and see what we can produce.
Good to hear that :) I've been devoted to this aamks project for almost
2 years now, so hopefully I have enough motivation. I work for The Main
School of Fire Service (University), Warsaw, Poland. Aamks is about
producing fires and evacuating people. The conditions of fire and smoke
affect agents' visibility, speeds, healths, etc. Our final goal is to
propose our approach to the National Fire Service as a measure for the
evaluation of buildings safety. The distinct thing about aamks is that
we run hundreds of such simulations and that we use quick CFAST fire
model, as opposed to the more popular FDS, which is precise but slow --
typicaly fire safety engineers run say 3 FDS simulations for one
building.

At first we used RVO2-2D and navigated with graphs in aamks, but then we
noticed the shortcomings and wanted navmesh and 3D. We inspected
blender, game engines, Recast, etc. but also the scientific works of
http://gamma.cs.unc.edu/, http://motion.cs.umn.edu/, etc.

So our Evac module needs a pretty much complete rewrite. This time we
would rather go into integration than into coding our own solutions.
Menge sounds the most promising right now, particularly that both our
projects have limited resources so we can help each other and that
there's a C++ coder our there -- you :) 

When it comes to the "plan". What I can offer is my motivation, quite a lot
of time for coding, python/linux/blender skills and willingness to
learn. I am a C++ beginner. Since you are the author of Menge it should
be easier for you to point what's the first thing to take care of. 
I could either 
a) inspect this: https://forums.ogre3d.org/viewtopic.php?t=62079 or 
b) just dive right into scripting blender to create and return the
navmesh. If you think Menge could require Blender as an
authoring/visualization tool, it might make sense to just handle the
problem of navmesh creation over to blender. Once we get the navmesh
from Blender we could run the simulation in Menge and then use Blender
again for visualization. I could do all the Blenderish part. We also
have the aamks infrastructure for js visualizations in web browsers, but
I like blender more.

Just today we found this announcement:
http://www.conferencemanager.dk/PED2018/event.html
we are considering going there, but if you go, we consider even more :)

-- 
Karol Kreński
tel. 517-302-055

**Comment by mimooh** [comment]
I was reading Menge docs and I was thinking of potential difficulties. Our workflow requires that the evacuation simulation runs such a master loop:
 1. Pause evacuation simulation 
 2. If there are fire simulation results for time T0, then read them and alter the evacuating agents parameters
 3. Run the evacuation simulation up to time T1 and pause again
Do you think Menge could make such pauses? And worse, would it allow for rereading these verbose  XML configs in each simulation step?

When it comes to navmesh: I think depending on Blender is not sufficient. Sooner or later we will need to address the situations where a fire moves from the room to the corridor and blocks the exit and in effect the navmesh needs to be recalculated as I understand it. So we will have these dynamic-non-human-obstacles situations. Looks like the real Recast integration instead of external Blender service would be more suitable, so I will see about this first.

**Comment by curds01** [comment]
So, integrating the two simulators is *very* doable. Menge has a `Task` element. At each time step, registered tasks get evaluated. A task is wide open. It can be any piece of code in the world. It's way to inject arbitrary logic into the simulation. Such a task could read external files (or monitor any other communication mechanism) and then modify the state of the simulator before taking the next step. It could also block to "pause" the simulation, waiting for data to come in. I think that'll be pretty easy.

It's much more interesting to do dynamic navigation meshes where paths can become occluded or clear again. Recast is one way of doing that, extending the current nav mesh implementation is another option. I'll take a look at recast and the current implementation to see which offers the best path at the right cost.

**Comment by mimooh** [comment]
The comments that recast integration is hard may be obsolete as some were from 2010. These documentation sites may be useful:
http://masagroup.github.io/recastdetour/group__recast.html
http://www.stevefsp.org/projects/rcndoc/prod/index.html

Also, Recast is integrated in game engines, such as godot, ogre3d, blender, so those repos may have some hints.

**Comment by curds01** [comment]
Here's a link to the python script I wrote to convert obj to my nav mesh representation.

https://github.com/curds01/MengeUtils/blob/master/objToNavMesh.py

It's not the most *robust* thing in the world. It gets angry if the obj has garbage, but it, at least, shows a mapping from understandable to my currently undocumented nav mesh format.

**Comment by mimooh** [comment]
First thing is that Menge installation and usage went quite smooth on linux. We were delighted to run and see the results of the examples. We need this thing in aamks! :) 

Second thing is that we couldn't find any python implementation of navmesh, so we coded our own, but it seems like you have some navmesh code. Pitty we haven't heard of it before. 

I was reading objToNavMesh.py and browsed thru your utils. So what is MengeUtils/navMesh.py doing?  Is menge/examples/core/globalNavSwap/navmesh.nav the representation of a navmesh? What you have and what is Menge lacking when it comes to navmeshes?

**Comment by curds01** [comment]
Yep. Menge has its own navigation mesh. :)

There are several `.nav` files that are all navigation meshes (ranging from very simple to more complex). 

`navMesh.py` provides the definition of the navigation mesh. Note: it's just the structures, no planning algorithms.  The `objToNavMesh.py` uses it to build a nav mesh and write out the representation. So, as long as you have access to vertices, edges, and faces, then you can follow the example to create a navigation mesh -- you should be able to pull `navMesh.py` straight into blender.

**Comment by mimooh** [comment]
This is how I understand navmesh:

The first part would be to create a navmesh. Recast does it, and we have
coded most of the below in python:

1. First you have obstacles, specified by vertices
2. You run a triangulation on these bag of vertices
3. You figure out which triangles are traversable
4. You figure out the relations between triangles - at the end you would
be moving in the world from P0 to P1 by traversing via adjacent
triangles 
5. Seems like for optimization these triangles can be merged into larger
convex polygons
6. The navmesh must be shrinked (inset) by taking agents' dimensions
under account -- this prevents agents from hitting the walls

Then there would be the spatial reasoning. Detour does it, and we have
also coded some navigation in python. There was that two legged
"creature" that would move its legs thru the vertices with the rules for
which leg to move. It would reach from P0 to P1, but this is where we
stopped to develop it. 

So which of the above are completed in Menge? I'd say that since the
navmesh must be only built once or twice for a scenario, the performance
is not that crucial and it can be done in python. Is this how you have
it? Then the navigation queries happen all the time, so you have this in
c++ I assume?

We have never written the navmesh representation to the file, hence I
was curious how one represents it. The file navmesh.nav is one of such
representations I assume. Is it the "obj" as you call it? And then you
would transform it to some other, like more standard representation? 

We don't need to export the navmesh to blender. We thought the blender
game engine would be our simulator, because it has navmesh. But then it
didn't work for us (lots of incorrections, agents would stop for no
reason, lack of control), so we cannot use blender as the simulator --
Menge has all we need it seems.

-- 
Karol Kreński
tel. 517-302-055

**Comment by mimooh** [comment]
Aaah, "obj", wouldn't it be this file format? :) go-detour uses obj.
https://en.wikipedia.org/wiki/Wavefront_.obj_file

**Comment by curds01** [comment]
You've got the vision.  Here's my take.

To have virtual agents move around a virtual environment, you need to represent which spaces are traversable and how they are connected. There are lots of ways of doing that. One way is a road map -- a bunch of points in the space that you connect with straight line segments. To get from one place to another, an agent finds the closest roadmap *point* to itself and its goal point, and then finds a path along all of the connected segments that get it from start to end.

Another way is to create a regular grid. Mark all of the cells that have obstacles in them. All of the remaining cells represent traversable space. Finding a path is finding a sequence of cells from the one the agent starts in to the one the agent wants to end in.

A navigation mesh is similar to a regular grid, except, it's adaptive. Instead of fixed squares (regardless of how big the space is), it has irregular cells that fill up the space. Then, you figure out which cell (or polygon) the agent is in and which one the goal position is in and find a path through adjacent cells.

So, there are two separate concepts: the navigation mesh itself and the queries on the navigation mesh.

The mesh is what recast creates. It does it with some sophisticated software that takes as input some arbitrary environment and attempts to automatically create a mesh that accounts for agent radius and height. That's *one* way to get a mesh. Another is to create it by hand (this is what Menge currently requires). I take a virtual environment and I create a mesh that represents everywhere I want agents to walk.

The second part of it is the queries. Given an agent position, where on the mesh are they? Given a goal position, where on the mesh is it? Given two polygons (start and goal), how do you find a path from one to the other?

Menge has a data structure that represents a navigation mesh. It also has the algorithms for placing agents on that mesh, finding goal points on the mesh, etc. However, it can be improved in the following ways:

1. Input; currently it requires a file in a *very* particular file format representing Menge's own custom representation of a navigation mesh. There are two possible improvements here:
  - Allow input of the mesh as an obj file and have it converted into a navigation mesh on the fly. In this case, the obj file *is* the navigable space -- someone has already done the work of defining the space and we're just changing representation.
  - Allow input of the *environment* as an obj file and we *infer* a navigation mesh (like recast does).
2. Performance
  - Menge's navigation mesh doesn't use any spatial acceleration structures to facilitate queries (i.e., where on the mesh is a point). Recast uses a bounding box tree (which is what *I* would use in Menge, I just haven't gotten around to it.)

There may be others.

I started looking into recast and detour. I think we can definitely get them into Menge. I wonder how helpful that will be. In terms of integrating Menge and aamks, it won't provide any meaningful functionality. Its primary benefit would be inferring the navigation mesh from a description of the environment. That's nice, but it's not *necessary*. Anyone who can move faces and vertices around in Blender can do that.

I propose we focus on those things that are most important to get aamks and Menge integrated and than shine up convenience features later.

**Comment by mimooh** [comment]
If you are saying we don't need to bother with Recast, that's fine with
me. I am not saying Menge's navmesh solution is insufficient,
particularly, that performance is not that much of an issue for aamks. I
just didn't know how much there already is in Menge. 

>   - Allow input of the mesh as an obj file and have it converted into
>   a navigation mesh on the fly. In this case, the obj file *is* the
>   navigable space -- someone has already done the work of defining the
>   space and we're just changing representation.
I like that. Should be less work to convert navmesh to another format,
than have all the queries adapted if we introduced a navmesh format that
is new to Menge.

> The mesh is what recast creates. It does it with some sophisticated
> software that takes as input some arbitrary environment and attempts
> to automatically create a mesh that accounts for agent radius and
> height. That's *one* way to get a mesh. Another is to create it by
> hand (this is what Menge currently requires). I take a virtual
> environment and I create a mesh that represents everywhere I want
> agents to walk.
We don't want the "by hand" solution, right? How about this go-recast
tool? The client is available right away, I used it. It respects all
these agent sizes, max walking slopes, etc. - cool. I would learn how to
feed it with my geometries and it returns the navmesh. Then we see about
converting it to what Menge likes. Is that what it takes?

**Comment by curds01** [comment]
I'm going to propose that we close this issue and work this out via email. You can email me at seanc@cs.unc.edu.
